In [1]:
import json
import numpy as np
import yaml
config = 'Antenna_confi/FYST_config'
from LaserMetrology import Antenna
import matplotlib.pyplot as plt

In [2]:
FYST = Antenna()

In [3]:
FYST = Antenna()
panel = FYST.M2.panels['12281']
#z0 = FYST.M2.surface.surface(panel.center[0], panel.center[1]) -30
q = 300
x,y =np.meshgrid(np.linspace(-q,q,2),np.linspace(-q,q,2))
x = np.append(x.T.ravel(),0) #+ np.random.normal(0,1,5)
y = np.append(np.flip(y).T.ravel(),0) #+ np.random.normal(0,1,5)

x_0 = x+panel.center[0]
y_0 = y+panel.center[1]
dr= 0.01 - 0.05*x/q +0.05*y/q -0.009*x*y/q**2 + 0.03*((x/q)**2+(y/q)**2)
z_0 = panel.surface.surface(x_0,y_0)
nx,ny,nz,N = panel.surface.normal_vector(x_0,y_0)
x_0 = x_0 - dr*nx
y_0 = y_0 - dr*ny
z_0 = z_0 - dr*nz

offset = 50# mm
x_meas,y_meas,z_meas = x_0 - offset*nx, y_0 - offset*ny, z_0 - offset*nz,

Meas_data = np.column_stack([x_meas,y_meas,z_meas])


print(dr*1000)

[179.  61.  61. -21.  10.]


In [4]:
a,b,c,d,e = panel.To_adjuster_position_Method1(Meas_data,offset)
a1,b1,c1,d1,e1 = panel.To_adjuster_position_Method2(Meas_data,offset)

108.68500742361682 33.933896625409766 33.98987564740067 -24.599248399103956 9.999829261619144
107.42092790436429 32.72538300140429 32.722225731725686 -26.001076150930615 9.999789059645387


In [5]:
p = 300
x,y =np.meshgrid(np.linspace(-p,p,2),np.linspace(-p,p,2))
x = np.append(x.T.ravel(),0)
y = np.append(np.flip(y).T.ravel(),0)
dz_meas= a + b*x +c*y +d*x*y + e*((x)**2+(y)**2)
print(dz_meas*1000)
dz_meas1= a1 + b1*x +c1*y +d1*x*y + e1*((x)**2+(y)**2)
print(dz_meas1*1000)


[182.05988419  63.87247296  63.9564415  -17.86649954   9.99982926]
[179.16409994  61.13119145  61.12645555 -20.96890614   9.99978906]


In [6]:
dz= 0.01 - 0.05*x/q +0.05*y/q -0.009*x*y/q**2 + 0.03*((x/q)**2+(y/q)**2)
print(dz*1000)
print((dz_meas - dz)*1000)
print((dz_meas1 - dz)*1000)

[179.  61.  61. -21.  10.]
[ 3.05988419e+00  2.87247296e+00  2.95644150e+00  3.13350046e+00
 -1.70738381e-04]
[ 0.16409994  0.13119145  0.12645555  0.03109386 -0.00021094]


In [7]:
FYST.M1.panels['11531'].center

[1342.4, 35.0]

In [8]:
FYST.M2.panels.keys()

dict_keys(['12391', '12491', '12591', '12691', '12791', '12281', '12381', '12481', '12581', '12681', '12781', '12881', '12171', '12271', '12371', '12471', '12571', '12671', '12771', '12871', '12971', '12161', '12261', '12361', '12461', '12561', '12661', '12761', '12861', '12961', '12151', '12251', '12351', '12451', '12551', '12651', '12751', '12851', '12951', '12141', '12241', '12341', '12441', '12541', '12641', '12741', '12841', '12941', '12131', '12231', '12331', '12431', '12531', '12631', '12731', '12831', '12931', '12221', '12321', '12421', '12521', '12621', '12721', '12821', '12311', '12411', '12511', '12611', '12711'])

In [9]:
import json
import numpy as np
import yaml
config = 'Antenna_confi/FYST_config'
from LaserMetrology import Antenna
import matplotlib.pyplot as plt

In [10]:
FYST = Antenna()

In [11]:
FYST.M2.surface._create_offset_surface(10)

In [12]:
FYST.M1.surface._create_offset_surface(-10)

In [13]:
FYST.M1.panels['11531'].surface.surface_offset(0,0)

array([[-10.]])